---
- hosts: web
  vars:
    se_linux_required: "TRUE"     #Set to "TRUE" to set SELinux File Type on vhost dir, set to "" to disable it.
  roles:
    - role: jamie.install-httpd
      httpd_vhost_directory: /srv

    - role: jamie.create_vhost
      vhost_webserver_address: webserver.example.local
      vhost_webserver_port: 8000

    - role: jamie.create_vhost
      vhost_webserver_address: jamie.example.local
      vhost_webserver_port: 8080
  handlers:
    - name : httpd_restart
      service:
        name: httpd
        state: restarted
    
    - name: firewalld_restart
      service:
        name: firewalld
        state: restarted
