---
- hosts: web
  vars:
    se_linux_required: "TRUE"     #Set to "TRUE" to set SELinux File Type on vhost dir, set to "" to disable it.
  roles:
    - role: jamie.install-httpd
      httpd_vhost_directory: /srv
    - role: jamie.create_vhost
      vhost_webserver_address: webserver.example.local
      vhost_webserver_port: 80
    - role: jamie.create_vhost
      vhost_webserver_address: webserver1.example.local
      vhost_webserver_port: 800
  handlers:
    - name : httpd_restart
      service:
        name: httpd
        state: restarted
    - name: firewalld_restart
      service:
        name: firewalld
        state: restarted
- hosts: web
  tasks:
    - setup:
- hosts: lb
  tags: lb
  vars:
    se_linux_required: "TRUE"     #Set to "TRUE" to set SELinux port type for HAProxy, set to "" to disable it.
  roles:
    - role: jamie.install-haproxy

  handlers:
    - name : haproxy_restart
      service:
        name: haproxy
        state: restarted
    - name: firewalld_restart
      service:
        name: firewalld
        state: restarted
