---
# tasks file for jamie.install-haproxy
- name: Install HAProxy
  yum:
    name: haproxy
    state: latest
- name: Start and enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes
- name: Create firewalld rule for http traffic inbound to the loadbalancer
  firewalld:
    port: "80/tcp"
    permanent: true
    state: enabled
  notify: firewalld_restart
- name: Get facts
  setup:
- name: Install HAProxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 644
  register: haproxy_restart
